### ISSUE TITLE
[Flickr][Photo model] Look like invalid casts

### ISSUE THREAD

**Issue by jooservices** [jooservices/XGallery#52]
` protected $casts = [
        'sizes' => 'json',
    ];`

ERROR
`[2020-06-22 00:11:01] local.ERROR: json_decode() expects parameter 1 to be string, array given {"exception":"[object] (ErrorException(code: 0): json_decode() expects parameter 1 to be string, array given at /Users/vietvu/Sites/www/XGallery/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php:719)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'json_decode() e...', '/Users/vietvu/S...', 719, Array)
#1 /Users/vietvu/Sites/www/XGallery/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(719): json_decode(Array, true)
#2 /Users/vietvu/Sites/www/XGallery/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(503): Illuminate\\Database\\Eloquent\\Model->fromJson(Array)
#3 /Users/vietvu/Sites/www/XGallery/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(357): Illuminate\\Database\\Eloquent\\Model->castAttribute('sizes', Array)
#4 /Users/vietvu/Sites/www/XGallery/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php(323): Illuminate\\Database\\Eloquent\\Model->getAttributeValue('sizes')
#5 /Users/vietvu/Sites/www/XGallery/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Eloquent/Model.php(157): Illuminate\\Database\\Eloquent\\Model->getAttribute('sizes')
#6 /Users/vietvu/Sites/www/XGallery/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1527): Jenssegers\\Mongodb\\Eloquent\\Model->getAttribute('sizes')
#7 /Users/vietvu/Sites/www/XGallery/app/Jobs/Flickr/FlickrSyncToGooglePhoto.php(67): Illuminate\\Database\\Eloquent\\Model->__get('sizes')`

**Comment by jooservices** [comment]
It should be resolved
